apiVersion: v1
kind: Service
metadata:
  name: todosrestclient
  labels:
    app: todosrestclient
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: todosrestclient